apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: test-go
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: tssc-quay-quay-tssc-quay.apps.cluster-cntlz.cntlz.sandbox481.opentlc.com/tssc/test:6cd3299680994b2f4708cc45dc0ef0258f6bcf75@sha256:b55cef4c98b6ac92c829a76cb2b114e6ae5da630120f7d61003931c8ad96b51b
        name: container-image  
